### ISSUE TITLE
Support for Let's Encrypt http challenge

### ISSUE THREAD

**Issue by csmith** [csmith/docker-automatic-nginx-letsencrypt#3]
It won't actually be that messy to do a HTTP challenge instead of DNS.

We can write a new .conf file to nginx-config defining just a server{} block listening for http traffic for the hostname(s), and serve the challenge data from the letsencrypt-data volume.

**Comment by ShaneMcC** [comment]
In addition to the above 2 pull-requests, there would need to be a `csmith/docker-letsencrypt-http-01` container or so with a `run.sh` something like

```bash
#!/usr/bin/env bash

interrupt() {
  echo
  echo "Caught ^C, exiting."
  exit 1
}

trap interrupt SIGINT

mkdir -p '/letsencrypt/well-known'

if [ -n "${ACCEPT_CA_TERMS:-}" ]; then
  DEHYDRATED_CMD="/dehydrated --accept-terms"
else
  DEHYDRATED_CMD="/dehydrated"
fi

while true; do
  $DEHYDRATED_CMD --cron --challenge http-01
  $DEHYDRATED_CMD --cleanup
  inotifywait --timeout 86400 /letsencrypt/domains.txt
  sleep 60
done
```

and `/config` needs:
```bash
WELLKNOWN=/letsencrypt/well-known
```

**Comment by csmith** [comment]
Thanks for the PRs!

https://github.com/csmith/docker-letsencrypt-http-01 added
