### ISSUE TITLE
Replace nginx hupper

### ISSUE THREAD

**Issue by csmith** [csmith/docker-automatic-nginx-letsencrypt#5]
The one in the compose file doesn't seem to work too well - I don't think you reliably get the particular inotify events it listens to for docker volumes.

It'd be nice to do nginx-specific stuff like test the config too.

**Comment by ShaneMcC** [comment]
Also it no longer works with the latest version of docker as it doesn't pass a host header with the signal request.

I submitted PR to him (https://github.com/masm/docker-inotify-signal-container/pull/1), but no response :(

In the interim, you may want to create your own fork which implements that patch.
